import { useState, useCallback } from 'react'
import { FileText, Presentation, Sheet, File as FilePdf, Download, Loader2 } from 'lucide-react'
import { motion } from 'framer-motion'
import { api } from '../utils/api'

export function DocsPage(): JSX.Element {
  const [pptTopic, setPptTopic] = useState('')
  const [pptStatus, setPptStatus] = useState('')
  const [pptLoading, setPptLoading] = useState(false)
  const [excelDesc, setExcelDesc] = useState('')
  const [excelStatus, setExcelStatus] = useState('')
  const [excelLoading, setExcelLoading] = useState(false)
  const [pdfTopic, setPdfTopic] = useState('')
  const [pdfStatus, setPdfStatus] = useState('')
  const [pdfLoading, setPdfLoading] = useState(false)
  const [jobsExportStatus, setJobsExportStatus] = useState('')
  const [jobsExportLoading, setJobsExportLoading] = useState(false)

  const generatePpt = useCallback(async () => {
    if (!pptTopic.trim()) return
    setPptLoading(true)
    setPptStatus('')
    try {
      const resp = await api('/documents/powerpoint', {
        title: pptTopic,
        slides: [
          { title: 'Overview', content: pptTopic, bullet_points: ['Key insights', 'Analysis', 'Recommendations'] },
          { title: 'Details', content: 'Generated by BARQ AI', bullet_points: ['Automated generation', 'Customizable'] },
        ],
      })
      if (resp && typeof resp === 'object') {
        const data = resp as { status?: string; file_path?: string }
        setPptStatus(data.file_path ? `Generated: ${data.file_path}` : data.status || 'Done')
      } else {
        setPptStatus('Generation failed')
      }
    } catch { setPptStatus('Generation failed') }
    setPptLoading(false)
  }, [pptTopic])

  const generateExcel = useCallback(async () => {
    if (!excelDesc.trim()) return
    setExcelLoading(true)
    setExcelStatus('')
    try {
      const resp = await api('/documents/excel', {
        title: excelDesc,
        sheets: [{ name: 'Sheet1', headers: ['Item', 'Value', 'Notes'], rows: [['Sample', '100', 'Generated by BARQ']] }],
      })
      if (resp && typeof resp === 'object') {
        const data = resp as { status?: string; file_path?: string }
        setExcelStatus(data.file_path ? `Generated: ${data.file_path}` : data.status || 'Done')
      } else {
        setExcelStatus('Generation failed')
      }
    } catch { setExcelStatus('Generation failed') }
    setExcelLoading(false)
  }, [excelDesc])

  const generatePdf = useCallback(async () => {
    if (!pdfTopic.trim()) return
    setPdfLoading(true)
    setPdfStatus('')
    try {
      const resp = await api('/documents/pdf', {
        title: pdfTopic,
        content: `# ${pdfTopic}\n\nGenerated by BARQ AI.`,
        template: 'professional',
      })
      if (resp && typeof resp === 'object') {
        const data = resp as { status?: string; file_path?: string }
        setPdfStatus(data.file_path ? `Generated: ${data.file_path}` : data.status || 'Done')
      } else {
        setPdfStatus('Generation failed')
      }
    } catch { setPdfStatus('Generation failed') }
    setPdfLoading(false)
  }, [pdfTopic])

  const exportJobs = useCallback(async () => {
    setJobsExportLoading(true)
    setJobsExportStatus('')
    try {
      const resp = await api('/documents/export/jobs')
      if (resp && typeof resp === 'object') {
        const data = resp as { status?: string; file_path?: string; count?: number }
        setJobsExportStatus(data.file_path ? `${data.count ?? 0} jobs exported to ${data.file_path}` : data.status || 'Done')
      } else {
        setJobsExportStatus('Export failed')
      }
    } catch { setJobsExportStatus('Export failed') }
    setJobsExportLoading(false)
  }, [])

  return (
    <div className="p-6 max-w-7xl mx-auto space-y-6">
      <motion.div initial={{ opacity: 0, y: -10 }} animate={{ opacity: 1, y: 0 }}>
        <h1 className="text-xl font-orbitron font-bold text-ghost tracking-wider">DOCUMENT GENERATION</h1>
        <p className="text-sm font-rajdhani text-dim-400 mt-1">Create PowerPoint presentations, Excel spreadsheets, and PDFs by voice</p>
      </motion.div>

      <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
        {[
          { icon: Presentation, accent: 'text-plasma', title: 'PowerPoint', desc: 'Generate presentations from a topic or outline', placeholder: 'e.g., "AI Trends 2025"', btn: 'Generate PPT', loading: pptLoading, topic: pptTopic, setTopic: setPptTopic, generate: generatePpt, status: pptStatus, cmd: 'Create 5-slide deck on Q3 sales' },
          { icon: Sheet, accent: 'text-neural', title: 'Excel', desc: 'Create spreadsheets, export job data to CSV', placeholder: 'Spreadsheet description...', btn: 'Generate Excel', loading: excelLoading, topic: excelDesc, setTopic: setExcelDesc, generate: generateExcel, status: excelStatus, cmd: 'Create expense spreadsheet' },
          { icon: FilePdf, accent: 'text-plasma', title: 'PDF', desc: 'Generate beautiful PDFs, invoices, and reports', placeholder: 'PDF content...', btn: 'Generate PDF', loading: pdfLoading, topic: pdfTopic, setTopic: setPdfTopic, generate: generatePdf, status: pdfStatus, cmd: 'Export report to PDF' },
        ].map((item, i) => {
          const Icon = item.icon
          return (
            <motion.div key={item.title} initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: i * 0.05 }} className="glass-card-hover">
              <Icon className={`w-8 h-8 ${item.accent} mb-3`} />
              <h3 className="text-sm font-rajdhani font-semibold text-ghost mb-1">{item.title}</h3>
              <p className="text-sm font-exo text-dim-400 mb-4">{item.desc}</p>
              <div className="flex gap-2 mb-2">
                <input type="text" value={item.topic} onChange={(e) => item.setTopic(e.target.value)} onKeyDown={(e) => e.key === 'Enter' && item.generate()} placeholder={item.placeholder} className="input-cyan flex-1 text-sm" />
                <button onClick={item.generate} disabled={item.loading} className="btn-cyan text-sm whitespace-nowrap">
                  {item.loading ? <Loader2 className="w-3 h-3 animate-spin inline" /> : null}
                  {item.btn}
                </button>
              </div>
              {item.status && <p className="text-xs font-exo text-neural mt-1 truncate">{item.status}</p>}
              <p className="text-xs text-dim-500 mt-2 font-exo">Say: &quot;{item.cmd}&quot;</p>
            </motion.div>
          )
        })}
      </div>

      <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.2 }} className="glass-card">
        <div className="flex items-center gap-2 mb-4">
          <FileText className="w-5 h-5 text-cyan-300" />
          <h3 className="text-sm font-orbitron font-bold text-ghost tracking-wider">Exports & Recent</h3>
        </div>
        <div className="flex items-center gap-3">
          <button onClick={exportJobs} disabled={jobsExportLoading} className="btn-cyan text-sm flex items-center gap-2">
            {jobsExportLoading ? <Loader2 className="w-4 h-4 animate-spin" /> : <Download className="w-4 h-4" />}
            Export Jobs to CSV
          </button>
          {jobsExportStatus && <span className="text-xs font-exo text-neural">{jobsExportStatus}</span>}
        </div>
      </motion.div>
    </div>
  )
}
